- name: write line
  lineinfile:
   path: /home/ansible/.bashrc
   insertbefore: #path:
   line: export JAVA_HOME=/opt/jdk1.8.0_212 
   state: present
- name: write line
  lineinfile:
   path: /home/ansible/.bashrc
   insertafter: export JAVA_HOME=/opt/jdk1.8.0_212
   line: export PATH=$PATH:/opt/jdk1.8.0_212/bin  
   state: present